# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys

class LoginUi(object):

    def setupUi(self, login, Focus, app):
        self.Focus = Focus
        self.app = app
        login.setObjectName("g")
        login.setFixedSize(400, 300)
        login.setWindowIcon(QtGui.QIcon("focus.png"))
        self.login = login
        self.lineEdit = QtWidgets.QLineEdit(login)
        self.lineEdit.setGeometry(QtCore.QRect(100, 100, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

        self.pushButton = QtWidgets.QPushButton(login)
        self.pushButton.setGeometry(QtCore.QRect(150, 190, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.pressed.connect(self.log_in)
        self.pushButton.setStyleSheet("""
            QPushButton{background-color: #9e095e;border-radius:1px;border:1px solid #9e095e ;display:inline-block;
            cursor:pointer;color:#ffffff;self.font-size:17px;padding:0px 0px;text-decoration:none;
            text-shadow:0px 1px 0px #2f6627;}
            QPushButton:hover{background-color:#b00b69 ;}
            QPushButton:active{	position:relative;top:1px;}
            QPushButton:disabled{background-color: #d98cb3; color: #602040}""")

        self.textBrowser = QtWidgets.QTextBrowser(login)
        self.textBrowser.setGeometry(QtCore.QRect(-1, 0, 412, 301))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("background-image: url(assets/log.jpg);")
        self.textBrowser.raise_()

        self.lineEdit.raise_()
        self.pushButton.raise_()

        self.re_translate_ui(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def re_translate_ui(self, g):
        _translate = QtCore.QCoreApplication.translate
        g.setWindowTitle(_translate("g", "Login"))
        self.pushButton.setText(_translate("g", "Login"))

    def log_in(self):
        if self.lineEdit.text() == self.Focus.system.password:
            self.lineEdit.setText("")
            self.Focus.widget.show()
            self.Focus.widget.setWindowState(self.login.windowState())
            self.login.hide()

            self.Focus.widget.activateWindow()

    def log_out(self):
        if not self.Focus.widget.isActiveWindow():
            self.Focus.widget.hide()
            self.login.show()



